# Generated by Django 5.2 on 2025-05-07 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='PROJECT TITLE', max_length=255)),
                ('description', models.TextField(blank=True, db_column='PROJECT DESCRIPTION', max_length=1000, null=True)),
                ('created_at', models.DateField(auto_now_add=True, db_column='CREATED AT')),
                ('created_by', models.ForeignKey(db_column='CREATED BY', on_delete=django.db.models.deletion.CASCADE, related_name='project_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='TASK TITLE', max_length=255)),
                ('description', models.TextField(blank=True, db_column='TASK DESCRIPTION', max_length=1000, null=True)),
                ('due_date', models.DateField(db_column='DUE DATE')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], db_column='STATUS')),
                ('created_at', models.DateField(auto_now_add=True, db_column='CREATED AT')),
                ('assigned_to', models.ForeignKey(db_column='RELATED USER', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='RELATED PROJECT', on_delete=django.db.models.deletion.CASCADE, related_name='task_project', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True, db_column='COMMENT TEXT', default='Comment Not Added', max_length=1000, null=True)),
                ('created_at', models.DateField(auto_now_add=True, db_column='CREATED AT')),
                ('commented_by', models.ForeignKey(db_column='COMMENTED BY', on_delete=django.db.models.deletion.DO_NOTHING, related_name='commented_user', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(db_column='TASK', on_delete=django.db.models.deletion.CASCADE, related_name='task_comment', to='core.task')),
            ],
        ),
    ]
